### ISSUE TITLE
api.calcofi.io not loading (error 502)

### ISSUE THREAD

**Issue by bbest** [CalCOFI/api#5]
When trying to visit https://api.calcofi.io, I see:

```
This page isn’t workingapi.calcofi.io is currently unable to handle this request.
HTTP ERROR 502
```

**Comment by bbest** [comment]
Logging into [rstdudio.calcofi.io](https://rstdudio.calcofi.io) as `bebest` and opening **Terminal** to try restarting and looking at logs, per the [README](https://github.com/CalCOFI/api#readme):

```bash
sudo -u shiny pm2 start --interpreter="Rscript" --image-name="run-api" '/share/github/api/run-api.R'
```

```
[PM2] Applying action restartProcessId on app [run-api](ids: 0)
[PM2] [run-api](0) ✓
[PM2] Process successfully started
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ run-api            │ fork     │ 2    │ errored   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
```


```bash
sudo -u shiny pm2 logs
```

```
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/shiny/.pm2/pm2.log last 15 lines:
PM2        |     at process._tickCallback (internal/process/next_tick.js:63:19)
PM2        | 2023-08-15T17:13:02: PM2 log: Stopping app:run-api id:0
PM2        | 2023-08-15T17:13:02: PM2 error: app=run-api id=0 does not have a pid
PM2        | 2023-08-15T17:13:10: PM2 log: App [run-api:0] starting in -fork mode-
PM2        | 2023-08-15T17:13:10: PM2 log: App [run-api:0] online
PM2        | 2023-08-15T17:13:10: PM2 error: Error: spawn Rscript ENOENT
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
PM2        |     at onErrorNT (internal/child_process.js:415:16)
PM2        |     at process._tickCallback (internal/process/next_tick.js:63:19)
PM2        | 2023-08-15T17:15:33: PM2 log: App [run-api:0] starting in -fork mode-
PM2        | 2023-08-15T17:15:33: PM2 log: App [run-api:0] online
PM2        | 2023-08-15T17:15:33: PM2 error: Error: spawn Rscript ENOENT
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
PM2        |     at onErrorNT (internal/child_process.js:415:16)
PM2        |     at process._tickCallback (internal/process/next_tick.js:63:19)

/home/shiny/.pm2/logs/run-api-out.log last 15 lines:
0|run-api  | LINE 6: ...date >= '2015-01-25' AND date <= '2020-01-26' AND ctd_bottle...
0|run-api  |                                                              ^
0|run-api  | HINT:  Perhaps you meant to reference the column "ctd_bottles.depth_m".
0|run-api  | >
0|run-api  | <Rcpp::exception: Failed to prepare query: ERROR:  column ctd_bottles.depthm does not exist
0|run-api  | LINE 6: ...date >= '2015-01-25' AND date <= '2020-01-26' AND ctd_bottle...
0|run-api  |                                                              ^
0|run-api  | HINT:  Perhaps you meant to reference the column "ctd_bottles.depth_m".
0|run-api  | >
0|run-api  | <simpleError in UseMethod("collect"): no applicable method for 'collect' applied to an object of class "NULL">
0|run-api  | <simpleError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required>
0|run-api  | <simpleError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required>
0|run-api  | <simpleError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required>
0|run-api  | <simpleError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required>
0|run-api  | <simpleError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required>

/home/shiny/.pm2/logs/run-api-error.log last 15 lines:
0|run-api  | Argument of class NULL cannot be used to set default value in OpenAPI Specifications.
0|run-api  | Running swagger Docs at http://127.0.0.1:8888/__docs__/
0|run-api  | SELECT 
0|run-api  |   DATE_PART('year'   , date) AS year, 
0|run-api  |   AVG(t_degc) AS val_avg, STDDEV(t_degc) AS val_sd, 
0|run-api  |   COUNT(*) AS n_obs
0|run-api  | FROM ctd_casts JOIN ctd_bottles USING (cast_count)
0|run-api  | WHERE TRUE AND TRUE AND TRUE AND TRUE
0|run-api  | GROUP BY DATE_PART('year'   , date) 
0|run-api  | ORDER BY year
0|run-api  | 
0|run-api  | 
0|run-api  | Error in setwd(old_wd) : cannot change working directory
0|run-api  | Calls: %>% -> pr_run -> <Anonymous> -> setwd
0|run-api  | Execution halted
```

**Comment by bbest** [comment]
I think that log is old.  Per the README, I ran in Rstudio **Terminal**:

```bash
# run the script in the background (&) so it doesn't stop
Rscript /share/github/api/run-api.R &
```
